### ISSUE TITLE
Budget/Account Codes/Employee End Point

### ISSUE THREAD

**Issue by filebound** [TheAlphaSchoolSystemPTYLTD/accounts-payable-integration#20]
A requirement from a lot of schools is to be able to retrieve approval amounts for employees at the account code level for all available budgets (i.e. this year and next years budget). are we able to create an end point that will allow us a far greater granular dive into budgets, account codes and employees.

**Comment by scottetass** [comment]
Hi,

Can I get a bit more understanding on this requirement, if it is still needed?

There is an endpoint, getCOA, which was created after this request which does return account responsibilities, including limit amounts. Does this satisfy the requirement?

Thanks, Scott

**Comment by scottetass** [comment]
Closing due to no response.
