### ISSUE TITLE
setPOInvoice fails when item prices differ from PO

### ISSUE THREAD

**Issue by BBCDigital** [TheAlphaSchoolSystemPTYLTD/accounts-payable-integration#27]
Currently the TASSweb API won't allow us to post PO invoices where line item prices differ from the PO. However, when an accounts person is manually entering an invoice, any changes they make to the lines or item prices automatically update the PO without error or warning and the invoice is submitted successfully. We are hoping to achieve this same functionality via the API.

We could foresee an optional parameter being added to the to API Method "setPOInvoice" to specify whether to force update any differing amounts or to fail the upload. Currently, this missing option is a deal-breaker for many schools we've been in contact with, who are wanting to automate their Accounts Payable system, as it causes a lot of double-handling and manual entry.

We are aware of the Deep Linking option for Purchase Orders but this is where the double-handling comes in as it still requires a user to log in and update the PO manually (generally after the line item details have already been entered/specified in whichever 3rd party application is attempting to automate this process).

We understand why there may be some reservation around enabling an option like this but that would seem to be negated by the fact a Tass Accounts user can already alter a PO from the Invoice posting screen. They don't have to open & edit the PO beforehand, they just specify which PO the invoice is linked to and can go ahead and alter the PO lines however they like.

**Comment by scottetass** [comment]
Hi,

There is an endpoint called editPOLine that will allow you to change line item values for the PO.
If you call this first, then call setPOInvoice, it should have the same effect.

There are no plans at this stage to change setPOInvoice to allow it to update PO line item values.

Thanks, Scott
