### ISSUE TITLE
Not getting email value in responsibly from getCOA

### ISSUE THREAD

**Issue by Kepli-Korrin** [TheAlphaSchoolSystemPTYLTD/accounts-payable-integration#32]
I am working with one of our clients and we are trying to get the responsibilities from the getCOA api. In the return there is an email field but when we query it its returning “”, I have done a teams session with the client but can’t see where they populate that field. As all they add is the user account. In the user account the email is populated

![image](https://user-images.githubusercontent.com/30275133/117221903-8d397580-ae4d-11eb-9cd9-c3ef3cd28419.png)

**Comment by leonseremelis-tass** [comment]
If you are still experiencing this issue, can we have some further information as to what type of user you are trying to retrieve (teacher/employee)?
