### ISSUE TITLE
setGLInvoice Endpoint Internal Server Error

### ISSUE THREAD

**Issue by codebreakerlegend2019** [TheAlphaSchoolSystemPTYLTD/accounts-payable-integration#33]
We are calling the setGLInvoice endpoint to post our invoice and we are getting 500 internal server error even though the invoice has been posted to Tass. We are getting "Invoice number already used" on the 2nd try. This issue is intermittent as well.

Can someone please check?

**Comment by bradftass** [comment]
Hi, can you please send an email to support@tassweb.com.au with the following details?
- the URL you're calling
- a copy of the JSON packet
- the app code that you're using

Please mention for it to be forwarded to Brad Fleming and I'll see what can be done.
