### ISSUE TITLE
New methods

### ISSUE THREAD

**Issue by ESPSolutions** [TheAlphaSchoolSystemPTYLTD/accounts-payable-integration#8]
Hi
Can we please request:
1. A method to return a list of Budgets
 - Acct_code
 - The total budget ie total of budj1_amt, budj2_amt, budj3_amt, budj4_amt, budj5_amt and budj6_amt
 - the amount remaining
2. A method to return Batches
 - Vouch_code
 - Pay_num
 - Apply_num
 - Apply_amt
 - Vend_code
 - vend abn
 - Inv_code

Let me know if you need more information.

**Comment by scottetass** [comment]
Hi,

Could you please let me know if this is still a requirement.

Some budget information is now available via the getCOA endpoint, although it does not return remaining budget amounts.

For point 2, getIsInvoicePaid will return information about whether invoices have been paid but it does not currently return any information regarding the invoice except for a true/false flag to say whether the invoice has been paid or not. If this is still a requirement then please let me know.

Thanks, Scott
